name: Release

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set up Git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Build for Linux
        run: |
          export GOOS=linux
          export GOARCH=amd64
          go build -o ./bin/ava-linux .
          git tag -d "linux-release" || true
          git push --delete origin "linux-release" || true
          git tag -a "linux-release" -m "Linux release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Linux tag
        run: |
          git push origin "linux-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Linux release
        uses: actions/create-release@v1
        with:
          tag_name: linux-release
          release_name: "Linux Release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ava-linux
          asset_name: ava-linux
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Windows
        run: |
          export GOOS=windows
          export GOARCH=amd64
          go build -o ./bin/ava-windows.exe .
          git tag -d "windows-release" || true
          git push --delete origin "windows-release" || true
          git tag -a "windows-release" -m "Windows release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Windows tag
        run: |
          git push origin "windows-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Windows release
        uses: actions/create-release@v1
        with:
          tag_name: windows-release
          release_name: "Windows Release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ava-windows.exe
          asset_name: ava-windows.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Mac
        run: |
          export GOOS=darwin
          export GOARCH=amd64
          go build -o ./bin/ava-mac .
          git tag -d "mac-release" || true
          git push --delete origin "mac-release" || true
          git tag -a "mac-release" -m "Mac release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Mac tag
        run: |
          git push origin "mac-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Mac release
        uses: actions/create-release@v1
        with:
          tag_name: mac-release
          release_name: "Mac Release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Mac binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ava-mac
          asset_name: ava-mac
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}